name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on
  GOPRIVATE: github.com/acuvity,go.acuvity.ai
  GOPROXY: https://proxy.golang.org,direct
  GOTOKEN: ${{ secrets.GO_PRIVATE_REPO_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.23"
          - "1.24"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: setup
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: build
        run: |
          git config --global url."https://acuvity:${GOTOKEN}@github.com/acuvity".insteadOf "https://github.com/acuvity"
          make

      - uses: acuvity/cov@1.0.2
        if: ${{ matrix.go == '1.24' }}
        with:
          main_branch: master
          cov_file: unit_coverage.out
          cov_threshold: "92"
          cov_mode: coverage
